### ISSUE TITLE
Check for player validity in player death timeout

### ISSUE THREAD

**Issue by LeonMrBonnie** [Whitee303/Git_Freeroam#3]
https://github.com/Whitee303/Git_Freeroam/blob/3e083f1ef19025265f2c0c5806437bcb3541f59e/server/index.js#L113-L117

Add a check for `player.valid` in the timeout handler, otherwise this will throw an error when the player disconnects before the timeout is finished.
Alternatively, save the timeout id on the player object, and clear the timeout on player disconnect. (This would be the cleaner approach as it wouldn't need to execute the timeout handler anymore, when it's not needed)

Also, the `return` in the last line is useless, and does nothing, it should be removed for cleaner code.

**Comment by Whitee303** [comment]
Fixed!
